using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using DataCore.Adapter.Common;

namespace DataCore.Adapter.Events {

    /// <summary>
    /// Base class describing a message generated by e.g. an alarms &amp; events system.
    /// </summary>
    public abstract class EventMessageBase {

        /// <summary>
        /// A unique identifier for the event.
        /// </summary>
        [Required]
        public string Id { get; set; }

        /// <summary>
        /// The UTC timestamp of the event.
        /// </summary>
        public DateTime UtcEventTime { get; set; }

        /// <summary>
        /// The priority associated with the event.
        /// </summary>
        public EventPriority Priority { get; set; }

        /// <summary>
        /// The event category.
        /// </summary>
        public string Category { get; set; }

        /// <summary>
        /// The event message.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Additional event properties.
        /// </summary>
        public IEnumerable<AdapterProperty> Properties { get; set; }

    }

}
