//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCore.Adapter.Grpc.Proxy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCore.Adapter.Grpc.Proxy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter ID is required..
        /// </summary>
        internal static string Error_AdapterIdIsRequired {
            get {
                return ResourceManager.GetString("Error_AdapterIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gRPC channel state is {0}. See inner results for remote adapter health..
        /// </summary>
        internal static string HealthCheck_ChannelStateDescription {
            get {
                return ResourceManager.GetString("HealthCheck_ChannelStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gRPC channel state is {0}..
        /// </summary>
        internal static string HealthCheck_ChannelStateDescriptionNoInnerResults {
            get {
                return ResourceManager.GetString("HealthCheck_ChannelStateDescriptionNoInnerResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gRPC Connection.
        /// </summary>
        internal static string HealthCheck_DisplayName_Connection {
            get {
                return ResourceManager.GetString("HealthCheck_DisplayName_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Adapter Health.
        /// </summary>
        internal static string HealthCheck_DisplayName_RemoteAdapter {
            get {
                return ResourceManager.GetString("HealthCheck_DisplayName_RemoteAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See inner results for remote adapter health..
        /// </summary>
        internal static string HealthCheck_GrpcNetClientDescription {
            get {
                return ResourceManager.GetString("HealthCheck_GrpcNetClientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote adapter does not implement health checks..
        /// </summary>
        internal static string HealthCheck_RemoteAdapterHealthNotSupported {
            get {
                return ResourceManager.GetString("HealthCheck_RemoteAdapterHealthNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while shutting down gRPC channel..
        /// </summary>
        internal static string Log_ChannelShutdownError {
            get {
                return ResourceManager.GetString("Log_ChannelShutdownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while registering an extension feature implementation: {0}.
        /// </summary>
        internal static string Log_ExtensionFeatureRegistrationError {
            get {
                return ResourceManager.GetString("Log_ExtensionFeatureRegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No implementation available for extension feature: {0}.
        /// </summary>
        internal static string Log_NoExtensionImplementationAvailable {
            get {
                return ResourceManager.GetString("Log_NoExtensionImplementationAvailable", resourceCulture);
            }
        }
    }
}
