//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCore.Adapter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCore.Adapter.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An absolute URI is required..
        /// </summary>
        public static string Error_AbsoluteUriRequired {
            get {
                return ResourceManager.GetString("Error_AbsoluteUriRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An absolute URI with one of the following schemes is required: {0}.
        /// </summary>
        public static string Error_AbsoluteUriWithSpecificSchemeRequired {
            get {
                return ResourceManager.GetString("Error_AbsoluteUriWithSpecificSchemeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the length of at least one array dimension..
        /// </summary>
        public static string Error_ArrayDimensionsMustBeSpecified {
            get {
                return ResourceManager.GetString("Error_ArrayDimensionsMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array element type is unsupported..
        /// </summary>
        public static string Error_ArrayElementTypeIsUnsupported {
            get {
                return ResourceManager.GetString("Error_ArrayElementTypeIsUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert an array variant to a non-array type..
        /// </summary>
        public static string Error_CannotConvertAnArrayVariantToANonArrayType {
            get {
                return ResourceManager.GetString("Error_CannotConvertAnArrayVariantToANonArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert a non-array variant to an array type..
        /// </summary>
        public static string Error_CannotConvertANonArrayVariantToAnArrayType {
            get {
                return ResourceManager.GetString("Error_CannotConvertANonArrayVariantToAnArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type cannot be decoded by this encoder..
        /// </summary>
        public static string Error_CannotDecodeType {
            get {
                return ResourceManager.GetString("Error_CannotDecodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type cannot be encoded by this encoder..
        /// </summary>
        public static string Error_CannotEncodeType {
            get {
                return ResourceManager.GetString("Error_CannotEncodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a content type..
        /// </summary>
        public static string Error_ContentTypeIsRequired {
            get {
                return ResourceManager.GetString("Error_ContentTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot specify a null data function name..
        /// </summary>
        public static string Error_DataFunctionCannotBeNull {
            get {
                return ResourceManager.GetString("Error_DataFunctionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate subscription topics are not allowed..
        /// </summary>
        public static string Error_DuplicateSubscriptionTopicsAreNotAllowed {
            get {
                return ResourceManager.GetString("Error_DuplicateSubscriptionTopicsAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot specify multiple write collections for the same tag..
        /// </summary>
        public static string Error_DuplicateTagWriteCollectionsAreNotAllowed {
            get {
                return ResourceManager.GetString("Error_DuplicateTagWriteCollectionsAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded object uses encoding type &apos;{0}&apos;, but this encoder supports encoding type &apos;{1}&apos;..
        /// </summary>
        public static string Error_EncodedObjectHasWrongEncoding {
            get {
                return ResourceManager.GetString("Error_EncodedObjectHasWrongEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot specify a null event message..
        /// </summary>
        public static string Error_EventMessageCannotBeNull {
            get {
                return ResourceManager.GetString("Error_EventMessageCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify an ID..
        /// </summary>
        public static string Error_IdIsRequired {
            get {
                return ResourceManager.GetString("Error_IdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval count must be greater than zero..
        /// </summary>
        public static string Error_IntervalCountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Error_IntervalCountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified JSON cannot be converted to an instance of {0}..
        /// </summary>
        public static string Error_InvalidJsonStructure {
            get {
                return ResourceManager.GetString("Error_InvalidJsonStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time span..
        /// </summary>
        public static string Error_InvalidTimeSpan {
            get {
                return ResourceManager.GetString("Error_InvalidTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time stamp..
        /// </summary>
        public static string Error_InvalidTimeStamp {
            get {
                return ResourceManager.GetString("Error_InvalidTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a valid URI..
        /// </summary>
        public static string Error_InvalidUri {
            get {
                return ResourceManager.GetString("Error_InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified JSON does not represent a Variant structure..
        /// </summary>
        public static string Error_InvalidVariantStructure {
            get {
                return ResourceManager.GetString("Error_InvalidVariantStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot specify a null or white space item type..
        /// </summary>
        public static string Error_ItemTypeCannotBeNull {
            get {
                return ResourceManager.GetString("Error_ItemTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a name..
        /// </summary>
        public static string Error_NameIsRequired {
            get {
                return ResourceManager.GetString("Error_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot specify a null name or ID..
        /// </summary>
        public static string Error_NameOrIdCannotBeNull {
            get {
                return ResourceManager.GetString("Error_NameOrIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot specify a null node ID..
        /// </summary>
        public static string Error_NodeIdCannotBeNull {
            get {
                return ResourceManager.GetString("Error_NodeIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrays can only be deserialized from JSON array elements..
        /// </summary>
        public static string Error_NotAJsonArray {
            get {
                return ResourceManager.GetString("Error_NotAJsonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection does not contain an encoder that can decode extension objects with a content type of &apos;{0}&apos;..
        /// </summary>
        public static string Error_NoValidDecodersFound {
            get {
                return ResourceManager.GetString("Error_NoValidDecodersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relative URI is required..
        /// </summary>
        public static string Error_RelativeUriRequired {
            get {
                return ResourceManager.GetString("Error_RelativeUriRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample interval must be greater than zero..
        /// </summary>
        public static string Error_SampleIntervalMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Error_SampleIntervalMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert an array with rank {0} to an array with rank {1}..
        /// </summary>
        public static string Error_SourceAndDestinationArraysHaveDifferentRanks {
            get {
                return ResourceManager.GetString("Error_SourceAndDestinationArraysHaveDifferentRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time cannot be greater than end time..
        /// </summary>
        public static string Error_StartTimeCannotBeGreaterThanEndTime {
            get {
                return ResourceManager.GetString("Error_StartTimeCannotBeGreaterThanEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time cannot be greater than or equal to end time..
        /// </summary>
        public static string Error_StartTimeCannotBeGreaterThanOrEqualToEndTime {
            get {
                return ResourceManager.GetString("Error_StartTimeCannotBeGreaterThanOrEqualToEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription topics cannot be null or white space..
        /// </summary>
        public static string Error_SubscriptionTopicsCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Error_SubscriptionTopicsCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one tag search filter field must be specified..
        /// </summary>
        public static string Error_TagSearchRequiresAtLeastOneFilter {
            get {
                return ResourceManager.GetString("Error_TagSearchRequiresAtLeastOneFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type does not define a {0} attribute..
        /// </summary>
        public static string Error_TypeIdIsUndefined {
            get {
                return ResourceManager.GetString("Error_TypeIdIsUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a type..
        /// </summary>
        public static string Error_TypeIsRequired {
            get {
                return ResourceManager.GetString("Error_TypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is unsupported..
        /// </summary>
        public static string Error_TypeIsUnsupported {
            get {
                return ResourceManager.GetString("Error_TypeIsUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host information has not been provided..
        /// </summary>
        public static string HostInfo_Unspecified_Description {
            get {
                return ResourceManager.GetString("HostInfo_Unspecified_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string HostInfo_Unspecified_Name {
            get {
                return ResourceManager.GetString("HostInfo_Unspecified_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No snapshot value was provided..
        /// </summary>
        public static string SnapshotTagValue_Unspecified_ErrorText {
            get {
                return ResourceManager.GetString("SnapshotTagValue_Unspecified_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string SnapshotTagValue_Unspecified_Value {
            get {
                return ResourceManager.GetString("SnapshotTagValue_Unspecified_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Quality.
        /// </summary>
        public static string TagValueStatus_Bad {
            get {
                return ResourceManager.GetString("TagValueStatus_Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Quality.
        /// </summary>
        public static string TagValueStatus_Good {
            get {
                return ResourceManager.GetString("TagValueStatus_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncertain Quality.
        /// </summary>
        public static string TagValueStatus_Uncertain {
            get {
                return ResourceManager.GetString("TagValueStatus_Uncertain", resourceCulture);
            }
        }
    }
}
