//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCore.Adapter.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCore.Adapter.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter creation delegate returned null..
        /// </summary>
        internal static string AdapterCreationDelegateReturnedNull {
            get {
                return ResourceManager.GetString("AdapterCreationDelegateReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapters implementing {0} should define at least one data function that can be called..
        /// </summary>
        internal static string AdapterDoesNotImplementAnyAggregates {
            get {
                return ResourceManager.GetString("AdapterDoesNotImplementAnyAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter does not implement any extension features..
        /// </summary>
        internal static string AdapterDoesNotImplementAnyExtensionFeatures {
            get {
                return ResourceManager.GetString("AdapterDoesNotImplementAnyExtensionFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adapter&apos;s feature set indicates that one or more of the following feature URIs should be present in the tag&apos;s set of supported features: {0}. Use the {1} class to build tag definitions that include details of supported features..
        /// </summary>
        internal static string AdapterFeaturesIndicateThatTagsShouldDefineSupportedFeatures {
            get {
                return ResourceManager.GetString("AdapterFeaturesIndicateThatTagsShouldDefineSupportedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adapter&apos;s feature set indicates that tags are not expected to have any entries in their supported features collection..
        /// </summary>
        internal static string AdapterFeaturesIndicateThatTagsShouldNotDefineSupportedFeatures {
            get {
                return ResourceManager.GetString("AdapterFeaturesIndicateThatTagsShouldNotDefineSupportedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapters should not return default({0}) as a health check result..
        /// </summary>
        internal static string AdapterShouldNotReturnDefaultHealthCheckResult {
            get {
                return ResourceManager.GetString("AdapterShouldNotReturnDefaultHealthCheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapters should not return null properties..
        /// </summary>
        internal static string AdaptersShouldNotReturnNullProperties {
            get {
                return ResourceManager.GetString("AdaptersShouldNotReturnNullProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation cannot end before it has started: &apos;{0}&apos; @ {1:dd-MMM-yyyy HH:mm:ss.fffffff}Z.
        /// </summary>
        internal static string AnnotationCannotEndBeforeItHasStarted {
            get {
                return ResourceManager.GetString("AnnotationCannotEndBeforeItHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations starting before the request start time must end after the request start time to be included in the query results: &apos;{0}&apos; @ {1:dd-MMM-yyyy HH:mm:ss.fffffff}Z.
        /// </summary>
        internal static string AnnotationMustEndAtOrAfterQueryStartTime {
            get {
                return ResourceManager.GetString("AnnotationMustEndAtOrAfterQueryStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation started after the query end time: &apos;{0}&apos; @ {1:dd-MMM-yyyy HH:mm:ss.fffffff}Z.
        /// </summary>
        internal static string AnnotationStartedAfterQueryEndTime {
            get {
                return ResourceManager.GetString("AnnotationStartedAfterQueryEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation time range does not overlap with query time range: &apos;{0}&apos; @ {1:dd-MMM-yyyy HH:mm:ss.fffffff}Z.
        /// </summary>
        internal static string AnnotationTimeRangeDoesNotOverlapWithQueryTimeRange {
            get {
                return ResourceManager.GetString("AnnotationTimeRangeDoesNotOverlapWithQueryTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null {0} item was emitted by the channel..
        /// </summary>
        internal static string ChannelContainedNullItem {
            get {
                return ResourceManager.GetString("ChannelContainedNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in the {0} collection should not be null..
        /// </summary>
        internal static string CollectionItemShouldNotBeNull {
            get {
                return ResourceManager.GetString("CollectionItemShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values for the following expected items were not received: {0}.
        /// </summary>
        internal static string ExpectedItemsWereNotReceived {
            get {
                return ResourceManager.GetString("ExpectedItemsWereNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descriptor returned for feature URI &apos;{0}&apos; was null..
        /// </summary>
        internal static string FeatureDescriptorIsNull {
            get {
                return ResourceManager.GetString("FeatureDescriptorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descriptor for feature URI &apos;{0}&apos; was requested, but the result has feature URI &apos;{1}&apos;..
        /// </summary>
        internal static string FeatureDescriptorUriMismatch {
            get {
                return ResourceManager.GetString("FeatureDescriptorUriMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature not implemented: {0}.
        /// </summary>
        internal static string FeatureNotImplemented {
            get {
                return ResourceManager.GetString("FeatureNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status of a health check result returned by the adapter does not match the aggregate status of the child health check results it contains..
        /// </summary>
        internal static string HealthCheckStatusDoesNotMatchAggregatedChildStatus {
            get {
                return ResourceManager.GetString("HealthCheckStatusDoesNotMatchAggregatedChildStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect annotation ID returned..
        /// </summary>
        internal static string IncorrectAnnotationIdReturned {
            get {
                return ResourceManager.GetString("IncorrectAnnotationIdReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one tag value was after the request end time. This is not allowed when the boundary type for the query is {0}..
        /// </summary>
        internal static string InsideBoundedRawQueryReturnedValuesAfterEndTime {
            get {
                return ResourceManager.GetString("InsideBoundedRawQueryReturnedValuesAfterEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one tag value was before the request start time. This is not allowed when the boundary type for the query is {0}..
        /// </summary>
        internal static string InsideBoundedRawQueryReturnedValuesBeforeStartTime {
            get {
                return ResourceManager.GetString("InsideBoundedRawQueryReturnedValuesBeforeStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page size for the request was {0}, but {1} items were returned..
        /// </summary>
        internal static string ItemCountIsGreaterThanPageSize {
            get {
                return ResourceManager.GetString("ItemCountIsGreaterThanPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the {0} method was null..
        /// </summary>
        internal static string MethodReturnedNullResult {
            get {
                return ResourceManager.GetString("MethodReturnedNullResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter implements {0}, but the &apos;{1}&apos; method used to generate input data for test &apos;{2}&apos; returned a value that indicates that the test should be skipped. Override {1} in your test class to return a non-null value if you wish to run this test..
        /// </summary>
        internal static string MissingTestInput {
            get {
                return ResourceManager.GetString("MissingTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected at least {0} {1} items, but only {2} items were received..
        /// </summary>
        internal static string NotEnoughResultsReturned {
            get {
                return ResourceManager.GetString("NotEnoughResultsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more operation descriptors for feature URI &apos;{0}&apos; were null..
        /// </summary>
        internal static string OneOrMoreOperationDescriptorsAreNull {
            get {
                return ResourceManager.GetString("OneOrMoreOperationDescriptorsAreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one tag value after the query end time was returned. When the boundary type for the query is {0}, a single value after the query end time is allowed..
        /// </summary>
        internal static string OutsideBoundedRawQueryReturnedTooManyValuesAfterEndTime {
            get {
                return ResourceManager.GetString("OutsideBoundedRawQueryReturnedTooManyValuesAfterEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one tag value before the query start time was returned. When the boundary type for the query is {0}, a single value before the query start time is allowed..
        /// </summary>
        internal static string OutsideBoundedRawQueryReturnedTooManyValuesBeforeStartTime {
            get {
                return ResourceManager.GetString("OutsideBoundedRawQueryReturnedTooManyValuesBeforeStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} query did not return any results..
        /// </summary>
        internal static string QueryDidNotReturnAnyResults {
            get {
                return ResourceManager.GetString("QueryDidNotReturnAnyResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query end time was {0:dd-MMM-yyyy HH:mm:ss.fffffff}Z, but a result was received with timestamp {1:dd-MMM-yyyy HH:mm:ss.fffffff}Z..
        /// </summary>
        internal static string QueryReturnedResultAfterEndTime {
            get {
                return ResourceManager.GetString("QueryReturnedResultAfterEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query start time was {0:dd-MMM-yyyy HH:mm:ss.fffffff}Z, but a result was received with timestamp {1:dd-MMM-yyyy HH:mm:ss.fffffff}Z..
        /// </summary>
        internal static string QueryReturnedResultBeforeStartTime {
            get {
                return ResourceManager.GetString("QueryReturnedResultBeforeStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag &apos;{0}&apos; (ID: &apos;{1}&apos;) contains entries in its {2} collection, but the search request specified that only basic information should be returned..
        /// </summary>
        internal static string TagSearchDidNotReturnRequestedResultFields {
            get {
                return ResourceManager.GetString("TagSearchDidNotReturnRequestedResultFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample time {0:dd-MMM-yyyy HH:mm:ss.fffffff}Z was not found in the expected sample times list. This indicates that multiple values were received with this timestamp for tag &apos;{1}&apos;..
        /// </summary>
        internal static string TimestampWasReceivedMultipleTimes {
            get {
                return ResourceManager.GetString("TimestampWasReceivedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a maximum of {0} results to be returned for tag &apos;{1}&apos;, but {2} results were returned..
        /// </summary>
        internal static string TooManyResultsReturnedForTag {
            get {
                return ResourceManager.GetString("TooManyResultsReturnedForTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve extension feature: {0}.
        /// </summary>
        internal static string UnableToResolveExtensionFeature {
            get {
                return ResourceManager.GetString("UnableToResolveExtensionFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data function &apos;{0}&apos; is unexpected..
        /// </summary>
        internal static string UnexpectedDataFunction {
            get {
                return ResourceManager.GetString("UnexpectedDataFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} items, but {1} items were received..
        /// </summary>
        internal static string UnexpectedItemCount {
            get {
                return ResourceManager.GetString("UnexpectedItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected {0} item was received: {1}.
        /// </summary>
        internal static string UnexpectedItemReceived {
            get {
                return ResourceManager.GetString("UnexpectedItemReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value was received for a tag that was not specified in the query: &apos;{0}&apos; (ID: &apos;{1}&apos;).
        /// </summary>
        internal static string UnexpectedTagValueReceived {
            get {
                return ResourceManager.GetString("UnexpectedTagValueReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with timestamp {0:dd-MMM-yyyy HH:mm:ss.fffffff}Z was not expected..
        /// </summary>
        internal static string UnexpectedTimestamp {
            get {
                return ResourceManager.GetString("UnexpectedTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write result returned an unknown correlation ID: {0}.
        /// </summary>
        internal static string UnexpectedWriteResultCorrelationIdReturned {
            get {
                return ResourceManager.GetString("UnexpectedWriteResultCorrelationIdReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null {0} value was received..
        /// </summary>
        internal static string ValueShouldNotBeNull {
            get {
                return ResourceManager.GetString("ValueShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values were not received for the following timestamps for tag &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ValuesWereNotReceivedForExpectedTimestamps {
            get {
                return ResourceManager.GetString("ValuesWereNotReceivedForExpectedTimestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write result correlation ID should not be null because a correlation ID was specified on all values that were written..
        /// </summary>
        internal static string WriteResultCorrelationIdExpected {
            get {
                return ResourceManager.GetString("WriteResultCorrelationIdExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write status indicates failure..
        /// </summary>
        internal static string WriteStatusIndicatesFailure {
            get {
                return ResourceManager.GetString("WriteStatusIndicatesFailure", resourceCulture);
            }
        }
    }
}
