//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCore.Adapter.Json {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCore.Adapter.Json.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the length of at least one array dimension..
        /// </summary>
        internal static string Error_ArrayDimensionsMustBeSpecified {
            get {
                return ResourceManager.GetString("Error_ArrayDimensionsMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON-encoded extension objects must have a content type of &apos;application/json&apos;..
        /// </summary>
        internal static string Error_InvalidExtensionObjectContentType {
            get {
                return ResourceManager.GetString("Error_InvalidExtensionObjectContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified JSON cannot be converted to an instance of {0}..
        /// </summary>
        internal static string Error_InvalidJsonStructure {
            get {
                return ResourceManager.GetString("Error_InvalidJsonStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified JSON does not represent a Variant structure..
        /// </summary>
        internal static string Error_InvalidVariantStructure {
            get {
                return ResourceManager.GetString("Error_InvalidVariantStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No JSON converter is available for type {0}..
        /// </summary>
        internal static string Error_NoJsonConverter {
            get {
                return ResourceManager.GetString("Error_NoJsonConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrays can only be deserialized from JSON array elements..
        /// </summary>
        internal static string Error_NotAJsonArray {
            get {
                return ResourceManager.GetString("Error_NotAJsonArray", resourceCulture);
            }
        }
    }
}
