//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCore.Adapter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AbstractionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AbstractionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCore.Adapter.AbstractionsResources", typeof(AbstractionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average value calculated over sample interval..
        /// </summary>
        public static string DataFunction_Avg_Description {
            get {
                return ResourceManager.GetString("DataFunction_Avg_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string DataFunction_Avg_Name {
            get {
                return ResourceManager.GetString("DataFunction_Avg_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of good-quality raw samples that have been recorded for the tag at each sample interval..
        /// </summary>
        public static string DataFunction_Count_Description {
            get {
                return ResourceManager.GetString("DataFunction_Count_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string DataFunction_Count_Name {
            get {
                return ResourceManager.GetString("DataFunction_Count_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signed difference between the earliest good-quality value and latest good-quality value in each sample interval..
        /// </summary>
        public static string DataFunction_Delta_Description {
            get {
                return ResourceManager.GetString("DataFunction_Delta_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta.
        /// </summary>
        public static string DataFunction_Delta_Name {
            get {
                return ResourceManager.GetString("DataFunction_Delta_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolates a value at each sample interval based on the raw values on either side of the sample time for the interval..
        /// </summary>
        public static string DataFunction_Interp_Description {
            get {
                return ResourceManager.GetString("DataFunction_Interp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolated.
        /// </summary>
        public static string DataFunction_Interp_Name {
            get {
                return ResourceManager.GetString("DataFunction_Interp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum good-quality value calculated over a fixed sample interval. The calculated value contains the actual timestamp that the maximum value occurred at..
        /// </summary>
        public static string DataFunction_Max_Description {
            get {
                return ResourceManager.GetString("DataFunction_Max_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string DataFunction_Max_Name {
            get {
                return ResourceManager.GetString("DataFunction_Max_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum good-quality value calculated over a fixed sample interval. The calculated value contains the actual timestamp that the minimum value occurred at..
        /// </summary>
        public static string DataFunction_Min_Description {
            get {
                return ResourceManager.GetString("DataFunction_Min_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string DataFunction_Min_Name {
            get {
                return ResourceManager.GetString("DataFunction_Min_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At each interval in a time range, calculates the percentage of raw samples in that interval that have bad-quality status..
        /// </summary>
        public static string DataFunction_PercentBad_Description {
            get {
                return ResourceManager.GetString("DataFunction_PercentBad_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Bad.
        /// </summary>
        public static string DataFunction_PercentBad_Name {
            get {
                return ResourceManager.GetString("DataFunction_PercentBad_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At each interval in a time range, calculates the percentage of raw samples in that interval that have good-quality status..
        /// </summary>
        public static string DataFunction_PercentGood_Description {
            get {
                return ResourceManager.GetString("DataFunction_PercentGood_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Good.
        /// </summary>
        public static string DataFunction_PercentGood_Name {
            get {
                return ResourceManager.GetString("DataFunction_PercentGood_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Calculation.
        /// </summary>
        public static string DataFunction_Property_StatusCalculation {
            get {
                return ResourceManager.GetString("DataFunction_Property_StatusCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method used to calculate the quality status for the function..
        /// </summary>
        public static string DataFunction_Property_StatusCalculation_Description {
            get {
                return ResourceManager.GetString("DataFunction_Property_StatusCalculation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Uncertain&quot; if any non-good quality values were skipped, or &quot;Good&quot; otherwise..
        /// </summary>
        public static string DataFunction_Property_StatusCalculation_ValueGoodUnlessNonGoodSkipped {
            get {
                return ResourceManager.GetString("DataFunction_Property_StatusCalculation_ValueGoodUnlessNonGoodSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst-case status of the samples used in the calculation..
        /// </summary>
        public static string DataFunction_Property_StatusCalculation_ValueWorstCase {
            get {
                return ResourceManager.GetString("DataFunction_Property_StatusCalculation_ValueWorstCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp Calculation.
        /// </summary>
        public static string DataFunction_Property_TimestampCalculation {
            get {
                return ResourceManager.GetString("DataFunction_Property_TimestampCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method used to calculate the timestamp for the function..
        /// </summary>
        public static string DataFunction_Property_TimestampCalculation_Description {
            get {
                return ResourceManager.GetString("DataFunction_Property_TimestampCalculation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp of maximum value.
        /// </summary>
        public static string DataFunction_Property_TimestampCalculation_ValueMaximum {
            get {
                return ResourceManager.GetString("DataFunction_Property_TimestampCalculation_ValueMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp of minimum value.
        /// </summary>
        public static string DataFunction_Property_TimestampCalculation_ValueMinimum {
            get {
                return ResourceManager.GetString("DataFunction_Property_TimestampCalculation_ValueMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absolute difference between the minimum good-quality value and maximum good-quality value in each sample interval..
        /// </summary>
        public static string DataFunction_Range_Description {
            get {
                return ResourceManager.GetString("DataFunction_Range_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string DataFunction_Range_Name {
            get {
                return ResourceManager.GetString("DataFunction_Range_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The standard deviation of all good-quality values in each sample interval.
        /// </summary>
        public static string DataFunction_StandardDeviation_Description {
            get {
                return ResourceManager.GetString("DataFunction_StandardDeviation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Deviation.
        /// </summary>
        public static string DataFunction_StandardDeviation_Name {
            get {
                return ResourceManager.GetString("DataFunction_StandardDeviation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variance of all good-quality values in each sample interval.
        /// </summary>
        public static string DataFunction_Variance_Description {
            get {
                return ResourceManager.GetString("DataFunction_Variance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance.
        /// </summary>
        public static string DataFunction_Variance_Name {
            get {
                return ResourceManager.GetString("DataFunction_Variance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows browsing of an adapter&apos;s asset model hierarchy..
        /// </summary>
        public static string Description_AssetModelBrowse {
            get {
                return ResourceManager.GetString("Description_AssetModelBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an adapter&apos;s asset model hierarchy to be searched..
        /// </summary>
        public static string Description_AssetModelSearch {
            get {
                return ResourceManager.GetString("Description_AssetModelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows subscribers to receive notifications when items on an adapter such as tags or asset model nodes are created, updated, or deleted..
        /// </summary>
        public static string Description_ConfigurationChanges {
            get {
                return ResourceManager.GetString("Description_ConfigurationChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows subscribers to receive event messages from an adapter in real-time..
        /// </summary>
        public static string Description_EventMessagePush {
            get {
                return ResourceManager.GetString("Description_EventMessagePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows subscribers to receive event messages from an adapter in real-time for specific topics..
        /// </summary>
        public static string Description_EventMessagePushWithTopics {
            get {
                return ResourceManager.GetString("Description_EventMessagePushWithTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an adapter&apos;s health status to be polled or subscribed to..
        /// </summary>
        public static string Description_HealthCheck {
            get {
                return ResourceManager.GetString("Description_HealthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the event message history on an adapter to be polled using a time range..
        /// </summary>
        public static string Description_ReadEventMessagesForTimeRange {
            get {
                return ResourceManager.GetString("Description_ReadEventMessagesForTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the event message history on an adapter to be polled using a cursor to define the starting point..
        /// </summary>
        public static string Description_ReadEventMessagesUsingCursor {
            get {
                return ResourceManager.GetString("Description_ReadEventMessagesUsingCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows polling of historical tag values using a visualisation-friendly aggregation..
        /// </summary>
        public static string Description_ReadPlotTagVaues {
            get {
                return ResourceManager.GetString("Description_ReadPlotTagVaues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows polling of historical tag values using a supported aggregate function to compute the results..
        /// </summary>
        public static string Description_ReadProcessedTagValues {
            get {
                return ResourceManager.GetString("Description_ReadProcessedTagValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows polling of raw, unprocessed historical tag values..
        /// </summary>
        public static string Description_ReadRawTagValues {
            get {
                return ResourceManager.GetString("Description_ReadRawTagValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows polling of snapshot (instantaneous) tag values..
        /// </summary>
        public static string Description_ReadSnapshotTagValues {
            get {
                return ResourceManager.GetString("Description_ReadSnapshotTagValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows polling of annotations on historical tag values..
        /// </summary>
        public static string Description_ReadTagValueAnnotations {
            get {
                return ResourceManager.GetString("Description_ReadTagValueAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows polling of tag values at specific timestamps in history..
        /// </summary>
        public static string Description_ReadTagValuesAtTimes {
            get {
                return ResourceManager.GetString("Description_ReadTagValuesAtTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows subscribers to receive snapshot tag value updates from an adapter in real-time..
        /// </summary>
        public static string Description_SnapshotTagValuePush {
            get {
                return ResourceManager.GetString("Description_SnapshotTagValuePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows retrieval of an adapter&apos;s tag definitions using the tag&apos;s ID or name..
        /// </summary>
        public static string Description_TagInfo {
            get {
                return ResourceManager.GetString("Description_TagInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an adapter&apos;s tag definitions to be searched..
        /// </summary>
        public static string Description_TagSearch {
            get {
                return ResourceManager.GetString("Description_TagSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an adapter to be used as an event sink for messages generated by external sources..
        /// </summary>
        public static string Description_WriteEventMessages {
            get {
                return ResourceManager.GetString("Description_WriteEventMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows tag values from an external source to be written directly into an adapter&apos;s history archive..
        /// </summary>
        public static string Description_WriteHistoricalTagValues {
            get {
                return ResourceManager.GetString("Description_WriteHistoricalTagValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the snapshot value of an adapter&apos;s tags to be updated from an external source..
        /// </summary>
        public static string Description_WriteSnapshotTagValues {
            get {
                return ResourceManager.GetString("Description_WriteSnapshotTagValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows tag value annotations on an adapter to be created, updated, and deleted..
        /// </summary>
        public static string Description_WriteTagValueAnnotations {
            get {
                return ResourceManager.GetString("Description_WriteTagValueAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Model Browsing.
        /// </summary>
        public static string DisplayName_AssetModelBrowse {
            get {
                return ResourceManager.GetString("DisplayName_AssetModelBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Model Search.
        /// </summary>
        public static string DisplayName_AssetModelSearch {
            get {
                return ResourceManager.GetString("DisplayName_AssetModelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Changes.
        /// </summary>
        public static string DisplayName_ConfigurationChanges {
            get {
                return ResourceManager.GetString("DisplayName_ConfigurationChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Message Push.
        /// </summary>
        public static string DisplayName_EventMessagePush {
            get {
                return ResourceManager.GetString("DisplayName_EventMessagePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic-Based Event Message Push.
        /// </summary>
        public static string DisplayName_EventMessagePushWithTopics {
            get {
                return ResourceManager.GetString("DisplayName_EventMessagePushWithTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check.
        /// </summary>
        public static string DisplayName_HealthCheck {
            get {
                return ResourceManager.GetString("DisplayName_HealthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time-Based Event Message History.
        /// </summary>
        public static string DisplayName_ReadEventMessagesForTimeRange {
            get {
                return ResourceManager.GetString("DisplayName_ReadEventMessagesForTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor-Based Event Message History.
        /// </summary>
        public static string DisplayName_ReadEventMessagesUsingCursor {
            get {
                return ResourceManager.GetString("DisplayName_ReadEventMessagesUsingCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Plot Tag Values.
        /// </summary>
        public static string DisplayName_ReadPlotTagVaues {
            get {
                return ResourceManager.GetString("DisplayName_ReadPlotTagVaues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Processed Tag Values.
        /// </summary>
        public static string DisplayName_ReadProcessedTagValues {
            get {
                return ResourceManager.GetString("DisplayName_ReadProcessedTagValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Raw Tag Values.
        /// </summary>
        public static string DisplayName_ReadRawTagValues {
            get {
                return ResourceManager.GetString("DisplayName_ReadRawTagValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Snapshot Tag Values.
        /// </summary>
        public static string DisplayName_ReadSnapshotTagValues {
            get {
                return ResourceManager.GetString("DisplayName_ReadSnapshotTagValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Annotations.
        /// </summary>
        public static string DisplayName_ReadTagValueAnnotations {
            get {
                return ResourceManager.GetString("DisplayName_ReadTagValueAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Tag Values At Times.
        /// </summary>
        public static string DisplayName_ReadTagValuesAtTimes {
            get {
                return ResourceManager.GetString("DisplayName_ReadTagValuesAtTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot Tag Value Push.
        /// </summary>
        public static string DisplayName_SnapshotTagValuePush {
            get {
                return ResourceManager.GetString("DisplayName_SnapshotTagValuePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Information.
        /// </summary>
        public static string DisplayName_TagInfo {
            get {
                return ResourceManager.GetString("DisplayName_TagInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Search.
        /// </summary>
        public static string DisplayName_TagSearch {
            get {
                return ResourceManager.GetString("DisplayName_TagSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Event Messages.
        /// </summary>
        public static string DisplayName_WriteEventMessages {
            get {
                return ResourceManager.GetString("DisplayName_WriteEventMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Historical Tag Values.
        /// </summary>
        public static string DisplayName_WriteHistoricalTagValues {
            get {
                return ResourceManager.GetString("DisplayName_WriteHistoricalTagValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Snapshot Tag Values.
        /// </summary>
        public static string DisplayName_WriteSnapshotTagValues {
            get {
                return ResourceManager.GetString("DisplayName_WriteSnapshotTagValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Annotations.
        /// </summary>
        public static string DisplayName_WriteTagValueAnnotations {
            get {
                return ResourceManager.GetString("DisplayName_WriteTagValueAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} feature is not implemented by the adapter..
        /// </summary>
        public static string Error_MissingAdapterFeature {
            get {
                return ResourceManager.GetString("Error_MissingAdapterFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not supported for a relative URI..
        /// </summary>
        public static string Error_RelativeUrisAreNotSupported {
            get {
                return ResourceManager.GetString("Error_RelativeUrisAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve property &apos;{0}&apos; because localization failed.  Type &apos;{1}&apos; is not public or does not contain a public static string property with the name &apos;{2}&apos;..
        /// </summary>
        public static string LocalizableString_LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizableString_LocalizationFailed", resourceCulture);
            }
        }
    }
}
